default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ruby
  password: root
  host: localhost

development:
  <<: *default
  database: chinchila_development

test:
  <<: *default
  database: chinchila_test

production:
  <<: *default
  database: chinchila_production
  username: ruby
  password: root
